export const CREATE_ITEM = "CREATE_ITEM";
export const LOAD_ITEM_GROUPS_SUCCESS = "LOAD_ITEM_GROUPS_SUCCESS";
export const LOAD_SELECTED_ITEM_GROUP_SUCCESS =
  "LOAD_SELECTED_ITEM_GROUP_SUCCESS";
export const CLEAR_ITEM_GROUPS = "CLEAR_ITEM_GROUPS";
export const SET_ITEM_GROUPS_PAGINATION = "SET_ITEM_GROUPS_PAGINATION";

export const DELETE_ITEM_GROUP_SUCCESS = "DELETE_ITEM_GROUP_SUCCESS";
export const NEW_ITEM_GROUP_SUCCESS = "NEW_ITEM_GROUP_SUCCESS";
